### ISSUE TITLE
トップページを作る

### ISSUE THREAD

**Issue by dynamis** [browserobo/browserobo.github.io#1]
最低限必要であろうコンテンツ

* W3C のページへのリンク (相互リンクにするのが望ましい)
http://www.w3.org/community/browserobo/
* プロジェクトの説明 (上記からの引用？)
* 開催イベントへのリンク、案内
https://browserobo.github.io/hackathon2017

あっても良いコンテンツ:
* 実装している例として CHIRIMEN コミュニティなどへのリンク
* そのほか。

note: イベントページなどはその開催国の母国語でするとしてもこのトップは W3C CG のなので英語想定

**Comment by kohichi000000** [comment]
素案

**Browsers and Robotics CG repository**
This site (repository) has information regarding Low Level APIs discussed in [W3C Browsers and Robotics CG](http://www.w3.org/community/browserobo/). Those APIs allow us to directly control physical devices via "web browser".

Links:
* [W3C Browsers and Robotics CG Page](http://www.w3.org/community/browserobo/)
* [Initail related activity (CHIRIMEN open hardware project)](https://chirimen.org/)
* API drafts:
  * [WebGPIO specification draft](https://github.com/browserobo/WebGPIO)
  * [WebI2C specification draft](https://github.com/browserobo/WebI2C)
* Events:
  * [Web x IoT makers hackathon 2017](https://browserobo.github.io/hackathon2017) (This event will be held in Japan on March 2017. Only Japanese.)

**Comment by kyoshino** [comment]
[トップページ](https://browserobo.github.io/) 公開しました。

**Comment by kohichi000000** [comment]
ありがとうございました
